/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_create_whc_incrementalupdate_Bspatch */

#ifndef _Included_com_create_whc_incrementalupdate_Bspatch
#define _Included_com_create_whc_incrementalupdate_Bspatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_create_whc_incrementalupdate_Bspatch
 * Method:    bspatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_create_whc_incrementalupdate_Bspatch_bspatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_create_whc_incrementalupdate_Bspatch
 * Method:    bsdiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_create_whc_incrementalupdate_Bspatch_bsdiff
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
